backend:
  name: git-gateway
  branch: pwa 

media_folder: 'static/img'
public_folder: /img

collections:
  - name: 'infographics'
    label: 'Infographics'
    folder: 'content/infographics'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    summary: '{{title}}/{{sub}}'
    path: '{{title}}/{{sub}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Locale', name: 'locale', widget: 'string' }
      - { label: 'Subcategory', name: 'sub', widget: 'string' }
      - { label: "Infographics", name: "infographics", widget: "list", summary: '{{fields.image}}', field: {label: Image, name: image, widget: image}}
